server: 
  port: 9003
spring: 
  application:  
    name: huahua-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.149.129:3306/huahua_qa?useUnicode=true&characterEncoding=UTF8
    username: root
    password: itcast
  jpa: 
    database: MySQL
    show-sql: true
jwt:
  config:
    key: huahuaCommunity
    ttl: 3600000     #过期时间一小时